### ISSUE TITLE
Plugin doesn't work on dokuwiki master

### ISSUE THREAD

**Issue by mpcjanssen** [neuralyzer/dokuwiki-plugin-revealjs#35]
The call to `_addCall` in `syntax/header.php` fails on the current Dokuwiki master. This is an internal dokuwiki call which is no longer publicly exposed:

```
05/Nov/2019:20:16:56 +0100 [ERROR 0 /] PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Doku_Handler::_addCall() in /var/www/dokuwiki/lib/plugins/revealjs/syntax/header.php:68
Stack trace:
#0 /var/www/dokuwiki/inc/parser/handler.php(234): syntax_plugin_revealjs_header->handle('====== Mark's w...', 5, 25, Object(Doku_Handler))
#1 /var/www/dokuwiki/inc/Parsing/Lexer/Lexer.php(268): Doku_Handler->plugin('====== Mark's w...', 5, 25, 'revealjs_header')
#2 /var/www/dokuwiki/inc/Parsing/Lexer/Lexer.php(195): dokuwiki\Parsing\Lexer\Lexer->invokeHandler('====== Mark's w...', 5, 25)
#3 /var/www/dokuwiki/inc/Parsing/Lexer/Lexer.php(155): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens('', '====== Mark's w...', '_plugin_revealj...', 25, 25)
#4 /var/www/dokuwiki/inc/Parsing/Parser.php(109): dokuwiki\Parsing\Lexer\Lexer->parse('\n\n\n{{monthcal:a...')
#5 /var/www/dokuwiki/inc/parserutils.php(216): dokuwiki\Parsing\Parser->parse('\n~~NOTOC~~\n\n~~N...')
#6 /var/www/dokuwiki/inc/parserutils.php(181): p_get_instructions('~~NOTOC~~\n\n~~NO.....
```

The proper fix is to replace the offending line with:

```
$handler->base($match,$state,$pos);
```

**Comment by mpcjanssen** [comment]
Change was introduced in https://github.com/splitbrain/dokuwiki/commit/8b1b81be965547272e7d20de20c2783fa59178cd
